[project]
name = "ct_agent_broker_ex_module"
version = "0.1.0"
description = "Exness broker module for CT Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0"
]
